disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - identifier_name
line_length:
  - 300 # warning
  - 400 # error
type_name:
    allowed_symbols: "_"
nesting:
    type_level: 3
